name: DMD-API-COMMON CI/CD Pipeline Testing 
on:
  push:
    branches:
      - main

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/dmdapicommon-0.0.1-SNAPSHOT.jar

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
    
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-1"

      - name: Upload package to S3 bucket
        run: aws s3 cp dmdapicommon-0.0.1-SNAPSHOT.jar s3://xml-deployment-s3-bucket/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name dmdapicommon \
          --auto-create-application \
          --source-bundle S3Bucket="xml-deployment-s3-bucket",S3Key="dmdapicommon-0.0.1-SNAPSHOT.jar" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-environment \
          --application-name dmdapicommon \
          --environment-name dmdapicommon-env-1 \
          --solution-stack-name "64bit Amazon Linux 2 v3.2.16 running Corretto 11" \
          --option-settings '[ { "Namespace": "aws:autoscaling:launchconfiguration", "OptionName": "IamInstanceProfile", "Value": "aws-elasticbeanstalk-ec2-role" } ]' \
          --version-label "ver-${{ github.sha }}"
